CREATE TABLE CONSUMER_DETAILS (
    meter_number VARCHAR(10)
);

INSERT INTO CONSUMER_DETAILS (meter_number)
VALUES 
    ('MTRX9012'),
    ('MTRY3456'),
    ('MTRZ7890'),
    ('MTRW4567'),
    ('MTRV1234'),
    ('MTRU5678'),
    ('MTRT8901'),
    ('MTRS2345'),
    ('MTRR6789'),
    ('MTRQ0123');

CREATE TABLE CONSUMER (
    CONSUMER_ID BIGINT NOT NULL PRIMARY KEY,
    METER_NUMBER VARCHAR(20) UNIQUE,
    TITLE VARCHAR(20),
    CONSUMER_NAME VARCHAR(100),
    EMAIL VARCHAR(50),
    MOBILE BIGINT,
    GENDER VARCHAR(20),
    USER_NAME VARCHAR(50),
    PASSWORD VARCHAR(50)
);

CREATE TABLE LOGIN (
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(50),
    CONSUMER_ID BIGINT,
    STATUS VARCHAR(20)
);

CREATE TABLE ADMIN_LOGIN (
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(50)
);

INSERT INTO ADMIN_LOGIN VALUES ('admin', 'Harsha@2005');

CREATE TABLE BILL (
    BILL_NUMBER INTEGER NOT NULL PRIMARY KEY,
    DUE_AMOUNT DOUBLE,
    BILL_AMOUNT DOUBLE,
    DUE_DATE VARCHAR(20),
    PENALTY DOUBLE,
    STATUS VARCHAR(20),
    METER_NUMBER VARCHAR(20)
);

CREATE TABLE PAYMENT (
    TRANSACTION_NUMBER INTEGER NOT NULL PRIMARY KEY,
    BILL_NUMBER INTEGER,
    PAID_AMOUNT DOUBLE,
    TRANSACTION_MODE VARCHAR(50),
    TRANSACTION_DATE VARCHAR(50),
    CONSUMER_ID BIGINT,
    METER_NUMBER VARCHAR(20)
);

CREATE TABLE COMPLAINT (
    COMPLAINT_ID INTEGER NOT NULL PRIMARY KEY,
    LANDMARK VARCHAR(50),
    SERVICE VARCHAR(50),
    CATEGORY VARCHAR(50),
    MOBILE BIGINT,
    CONTACT VARCHAR(50),
    PROBLEM VARCHAR(200),
    ADDRESS VARCHAR(200),
    COMPLAINT_STATUS VARCHAR(200),
    CONSUMER_ID BIGINT
);

ALTER TABLE BILL
ADD CONSTRAINT fk_bill
FOREIGN KEY (METER_NUMBER) REFERENCES CONSUMER (METER_NUMBER);

ALTER TABLE COMPLAINT
ADD CONSTRAINT fk_complaint
FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMER (CONSUMER_ID);

ALTER TABLE PAYMENT
ADD CONSTRAINT fk_payment
FOREIGN KEY (BILL_NUMBER) REFERENCES BILL (BILL_NUMBER);

ALTER TABLE LOGIN
ADD CONSTRAINT fk_login
FOREIGN KEY (CONSUMER_ID) REFERENCES CONSUMER (CONSUMER_ID);
